<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=admin.structure.first
 * [END_COT_EXT]
 */
 
/**
 * plugin Category Editor for Cotonti Siena
 * 
 * @package cateditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
if($m == 'structure')
{
	cot_redirect(cot_url('admin', 'm=other&p=cateditor', '', true));
}
//хук надо еще кудато