<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=tools
 * [END_COT_EXT]
 */
 
/**
 * plugin Category Editor for Cotonti Siena
 * 
 * @package cateditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');
require_once cot_incfile('cateditor', 'plug');
require_once cot_incfile('cateditor', 'plug', 'structure');
require_once cot_langfile('cateditor', 'plug');

cot_rc_add_file($cfg['plugins_dir'].'/cateditor/lib/jquery.nestable.js');
cot_rc_add_file($cfg['plugins_dir'].'/cateditor/lib/jquery.cookie.js');
cot_rc_add_file($cfg['plugins_dir'].'/cateditor/lib/jquery.nestable.css');
cot_rc_add_file($cfg['plugins_dir'].'/cateditor/lib/cateditor.js');

/* === Hook === */
foreach (cot_getextplugins('admin.structure.first') as $pl)
{
	include $pl;
}
/* ===== */
//cot_rc_link_file($cfg['plugins_dir'].'/banners/tpl/admin.css');
// Роутер
// Only if the file exists...
if (is_array($extension_structure) && count($extension_structure) == 1 && ((cot_plugin_active($extension_structure[0]) || cot_module_active($extension_structure[0]))))
{
	$n = $extension_structure[0];
}

$sub = (empty($n)) ? 'list' : 'editor';

if(!empty($n))
{
	$cot_structure = new structure($n);
	$is_module = (cot_module_active($n));
	
	if (file_exists(cot_incfile($n, $is_module ? 'module' : 'plug')))
	{
		require_once cot_incfile($n, $is_module ? 'module' : 'plug');
	}
}
if(!empty($a) && file_exists(cot_incfile('cateditor', 'plug', 'admin.'.$sub.'.'.$a)))
{
	require_once cot_incfile('cateditor', 'plug', 'admin.'.$sub.'.'.$a);
}
if (file_exists(cot_incfile('cateditor', 'plug', 'admin.'.$sub)))
{
	$t = new XTemplate(cot_tplfile('cateditor.admin.'.$sub, 'plug'));
	require_once cot_incfile('cateditor', 'plug', 'admin.'.$sub);
	cot_display_messages($t);
	$t->parse('MAIN');
	$adminmain = $t->text('MAIN');
}
else
{
	// Error page
	cot_die_message(404);
	exit;
}
