<?php


/**
 * [BEGIN_COT_EXT]
 * Code=cateditor
 * Name=Category Editor
 * Category=utilities-tools
 * Description=Edit Cat
 * Version=1.0.0
 * Date=2015-06-09
 * Author=esclkm
 * Copyright=Copyright (c) esclkm, http://littledev.ru/ 2008-2015
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin Category Editor for Cotonti Siena
 * 
 * @package cateditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>