<?php
/**
 * plugin Category Editor for Cotonti Siena
 * 
 * @package cateditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['new_category'] = 'Новая категория';
$L['parent_category'] = 'Родительская категория';
$L['auto_generation'] = 'Оставьте пустым, чтобы автоматически сгенерировать';
$L['Save_order'] = "Сохранить порядок";
$L['updated_order'] = "Категорий, у которых обновлен порядок";
$L['updated_order_none'] = "Ни у одной категории не обновлен порядок";